### ISSUE TITLE
Locality data

### ISSUE THREAD

**Issue by tucotuco** [rom-vertnet/mammalogyspecimens#22]
I downloaded the Darwin Core archive for the mammal data from the ROM IPT and find that locality and verbatimLocality are empty except for for a few that have what looks like a georeferenceRemark, such as "Ontario MaNIS Georeferencing in progress by Brad Millen, 2012; SMW edits to ROMM where LOCNM errors. O'BRIEN TOWNSHIP -> KAPUSKASING; O'BRIEN TO ORTP". Is there a mismapping? Or are the localities intentionally withheld?

**Comment by bradmROM** [comment]
This is probably a mistake in mapping due to corruption of their Table of Record that happened and was restored from backup.  I think that this issue reflects greater issues with that table.  Prob have to restore from much earlier than what was done.  

F&*^^/$

Going to check it out after my lunch.  Thanks for pointing this out.

Once I sort these things I will update again.......

How about all of the orphan semicolons in other providers? Is that a priority with them or not. A simple fix for their Higher geography and classification etc.

Just a thought that has been bouncing around in my head. 

Sent from Brad's Samsung Galaxy Mobile Note 3

<div>-------- Original message --------</div><div>From: John Wieczorek <notifications@github.com> </div><div>Date:2015-04-01  11:43 AM  (GMT-05:00) </div><div>To: rom-vertnet/mammalogyspecimens <mammalogyspecimens@noreply.github.com> </div><div>Subject: [mammalogyspecimens] Locality data (#22) </div><div>
</div>

**Comment by tucotuco** [comment]
If you mean using the now-recommended separator ' | ', then yes, go ahead and use this opportunity to set that as well. Preparations is another field where that is likely relevant. Perhaps recordedBy too?

If that is not what you are talking about, can you elaborate?

**Comment by bradmROM** [comment]
I needed to find a georef so searched and retrieved a series of specimen data. Noted that a lot of providers have a lot of orphans ";" from aggregating data into from other fields. Like Higher Geography from locality fields. 

CAS is one and sometimes I noted that a lot of data has quotes as if from a comma delimited export and re-import with " as one of the separators.

**Comment by bradmROM** [comment]
Sometimes whole data in fields are surrounded by quotes. I.e. recordedBy

**Comment by bradmROM** [comment]
Aside from all of this the ROM has gone with TMS - Gallery Systems Collections Management System. Starting tomorrow, first meeting.

>>> John Wieczorek <notifications@github.com> 2015-04-01 1:07 PM >>>
If you mean using the now-recommended separator ' | ', then yes, go ahead and use this opportunity to set that as well. Preparations is another field where that is likely relevant. Perhaps recordedBy too?

If that is not what you are talking about, can you elaborate?

---

**Comment by bradmROM** [comment]
Diagnosed the problems with Mammalogy and will update with all of your requirements ASAP. Going to spend the rest of the day when data is restored checking the table beforehand.
